### ISSUE TITLE
beebot should respond to the channel/DM where showme was typed

### ISSUE THREAD

**Issue by allred** [itzo/python#1]
if you say showme in a DM, beebot replies in general

**Comment by itzo** [comment]
commit 4e24b985e115541d84b6ffc33369f9f40f5eb9e5
Author: itzo <me@itzo.org>
Date:   Tue Jan 17 22:04:59 2017 -0500

    response for reactions not in the db added
    respond in channel where asked for top reaction

M       slack/beebot.py
