### ISSUE TITLE
beebot from_user can be same as to_user

### ISSUE THREAD

**Issue by allred** [itzo/python#2]
This would open the possibility of starting a new channel, inviting beebot and manipulating your own score by adding reactions to your own posts.  Also, might want to have a list of  "valid channels" where beebot logs the data to prevent similar collusion.

**Comment by itzo** [comment]
commit c6044a4ca7f25dcdaf6d18915c2497f9c0df9acd
Author: itzo <me@itzo.org>
Date:   Tue Jan 17 20:22:48 2017 -0500

    from_user can't be the same as to_user, otherwise the system can be gamed

M       slack/beebot.py
